theme = "basics"

languagecode = "en"

paginate = 20
canonifyurls = true
baseurl = "https://nclandrei.com"
title = "Andrei-Mihai Nicolae"

[params] # theme parameters
    author = "Andrei-Mihai Nicolae"
    github = "nclandrei"
    info = "Backend and distributed systems developer. Also a gopher." 
    description = "Andrei-Mihai Nicolae's personal website"
    keywords = "blog,developer,engineer,personal,golang,distributed,backend,cloud"